[View in Colaboratory](https://colab.research.google.com/github/abhisack/MLCC/blob/master/numpy-scratch.ipynb)

In [0]:
import numpy as np

In [0]:
a= np.array([1,2,3,4,5])

In [7]:
print(a)

[1 2 3 4 5]


In [0]:
v = np.array([1,4,5],)

In [9]:
v = np.array([1,4,5,6,7],
            [2,4,5,6,7],
            [2,4,5,8,1])

ValueError: ignored

In [10]:
v = np.array([1,4,5,6,7],[2,4,5,6,7],[2,4,5,8,1])

ValueError: ignored

In [0]:
v = np.array([[1,4,5,6,7],[2,4,5,6,7],[2,4,5,8,1]])

In [12]:
print(v)

[[1 4 5 6 7]
 [2 4 5 6 7]
 [2 4 5 8 1]]


In [13]:
print(v[0][1])

4


In [0]:
v1 = v+v

In [15]:
print(v1)

[[ 2  8 10 12 14]
 [ 4  8 10 12 14]
 [ 4  8 10 16  2]]


In [0]:
v2 = v*v

In [17]:
print(v2)

[[ 1 16 25 36 49]
 [ 4 16 25 36 49]
 [ 4 16 25 64  1]]


In [18]:
import time
import sys
S = range(1000)
print(sys.getsizeof(3)*len(5))

D= np.arrange(1000)
print(D.size*D.itemsize)

TypeError: ignored

In [19]:
import time
import sys
S= range(1000)
print(sys.getsizeof(3)*len(S))

D= np.arrange(1000)
print(D.size*D.itemsize)

28000


AttributeError: ignored

In [20]:
import time
import sys
S= range(1000)
print(sys.getsizeof(3)*len(S))

D= np.arrange(1000)
print(D.size*D.itemsize)

28000


AttributeError: ignored

In [21]:
import numpy as np
import time
import sys
S= range(1000)
print(sys.getsizeof(3)*len(S))

D= np.arrange(1000)
print(D.size*D.itemsize)

28000


AttributeError: ignored

In [22]:
import numpy as np
import time
import sys
S= range(1000)
print(sys.getsizeof(3)*len(S))

D= np.arange(1000)
print(D.size*D.itemsize)

28000
8000


In [23]:
import time
import sys

SIZE = 10

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2= np.arange(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start = time.time()
result = A1+A2
print((time.time()-start)*1000)

0.12326240539550781
0.14352798461914062


In [24]:
import time
import sys

SIZE = 10

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2= np.arange(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start = time.time()
result = A1+A2
print((time.time()-start)*1000)

0.08392333984375
0.08130073547363281


In [0]:
a = np.array([[1,2,3],[1,2,7],[6,7,8]])

In [0]:
a = np.array([(1,2,3), (4,5,6)])
print(a.nidm

In [29]:
a= np.zeros(2,3,4)

TypeError: ignored

In [30]:
a= np.zeroes(2,3,4)

AttributeError: ignored

In [31]:
a.dtype

dtype('int64')

In [0]:
b = np.array([1,2,3], dtype= 'int32')

In [33]:
print(b.dtype)

int32


In [34]:
c= np.array([(18,9),(4,5),(4,2)])
print(c[0:2,0])

[18  4]


In [35]:
c= np.array([(18,9),(4,5),(4,2)])
print(c[0:3,0])

[18  4  4]


In [0]:
d= np.linspace(1,10,2)

In [37]:
print(d)

[ 1. 10.]


In [39]:
e = np.array([1,2,3,4,5])
print(e.max())

5


In [0]:
a1= np.array([[2,4,5],[4,7,8],[9,2,4]])
a2 = np.array([[2,8,1],[4,7,2],[3,1,4]])

In [42]:
print(a1+a2)
print(a1*a2)
print(a1-a2)
print(a1/a2)

[[ 4 12  6]
 [ 8 14 10]
 [12  3  8]]
[[ 4 32  5]
 [16 49 16]
 [27  2 16]]
[[ 0 -4  4]
 [ 0  0  6]
 [ 6  1  0]]
[[1.  0.5 5. ]
 [1.  1.  4. ]
 [3.  2.  1. ]]


In [43]:
print(np.ravel(a1))

[2 4 5 4 7 8 9 2 4]


In [44]:
foo = np.zeroes(2,3)

AttributeError: ignored

In [45]:
foo = np.zeros(2,3)

TypeError: ignored

In [46]:
foo = np.zeroes((2,3))

AttributeError: ignored